### PR TITLE
Real diff (all the inserts/removes) on full update

### PR DESCRIPTION
**Pull request by andykog**
```swift
var x = MutableCollectionProperty(["A"])
x.value = ["B"]
```
should generate `CollectionChange.Composite` of `.Remove(0, "A")` and `.Insert(0, "B")` because this is what actially happen.
+ It solves the problem of connecting `MutableCollectionProperty` with `UITableView`

### CODE REVIEW

**Comment by pepibumur** [comment]
@andykog what is `jflinter/Dwifft` for?

**Comment by andykog** [comment]
@pepibumur For diff function https://github.com/jflinter/Dwifft/blob/master/Dwifft/Dwifft.swift#L75
Of course, it can be copy/pasted…

**Comment by andykog** [comment]
I messed up with gitmodules, trying to fix

**Comment by andykog** [comment]
fixed

**Comment by pepibumur** [comment]
But what I mean @andykog is if we can have that feature without using the Framework. I'm try to avoid dependencies, just only the reactive frameworks.

**Comment by andykog** [comment]
No problem, done

**Comment by andykog** [comment]
Pushed fix :-)

**Comment by pepibumur** [comment]
Great! merging @andykog

**Pull request merged**
